---
- name: Use role main file
  hosts: all
  become: true

  pre_tasks:
    - name: Deploy NFS Server
      ansible.builtin.debug:
        msg: "Starting NFS server deployment!"

    # - ansible.builtin.debug:
    #     msg: "Starting NFS server deployment!"

- name: Configure NFS servers
  hosts: nfs_server
  roles:
    - server

  post_tasks:
    - ansible.builtin.debug:
        msg: "The NFS server was deployed successfully!"

  pre_tasks:
    - ansible.builtin.debug:
        msg: "Starting NFS clients deployment!"

- name: Configure NFS clients
  hosts: nfs_clients
  roles:
    - client

  post_tasks:
    - ansible.builtin.debug:
        msg: "The NFS clients were deployed successfully!"
...
